### ISSUE TITLE
Web socket connection error

### ISSUE THREAD

**Issue by guneteroglu** [Emotiv/cortex-example#102]
Sometimes, when running connectToServer(), I get the following message:

   Process: com.hms2017.atbdisleksiv2, PID: 1326
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hms2017.atbdisleksiv2/com.hms2017.atbdisleksiv2.activity.MainActivity}: java.lang.IllegalStateException: WebSocketClient objects are not reuseable
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.IllegalStateException: WebSocketClient objects are not reuseable
        at org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:138)
        at com.emotiv.cortexv2example.websocket.WebSocketManager.connect(WebSocketManager.java:100)
        at com.hms2017.atbdisleksiv2.activity.MainActivity.connectToServer(MainActivity.java:288)
        at com.hms2017.atbdisleksiv2.activity.MainActivity.onCreate(MainActivity.java:1197)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by nguoithichkhampha** [comment]
@guneteroglu, seems this is a problem on your code.Sorry, we can not help you to resolve. if run our example and have any issue, you can reopen this ticket.
