### ISSUE TITLE
help, how can I run on nodejs.

### ISSUE THREAD

**Issue by Andrez-Flores** [Emotiv/cortex-example#116]
Operating system: windows 10
language version:nodejs 10.15
Cortex version: 

help, how can I run on nodejs.
I enter the data that asks but I get error

terminal:
(node:16180) UnhandledPromiseRejectionWarning: ReferenceError: numbers is not defined
    at client.ready.then (D:\*\cortex-example-master\nodejs\index.js:7:18)
(node:16180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Bonfs** [comment]
Operating system: Windows 10 and MacOS Mojave 10.14.4
language version: nodejs 10.16
Cortex version: 2.0.0

I don't know if is related problem but I can't run Nodejs too. My terminal message is different.
None of Nodejs examples worked for me.
terminal:
~> node index.js 
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 14.160.32.18:54321
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at ClientRequest.req.on (/Users/developer/Documents/projects/cortex-example/nodejs/node_modules/ws/lib/websocket.js:554:15)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by nguoithichkhampha** [comment]
@Bonfs , you are working with Cortex v2. please run example from this repo
https://github.com/Emotiv/cortex-v2-example

**Comment by Bonfs** [comment]
@nguoithichkhampha , I'm not using Cortex v2 Examples :(
I just open the link from documentation. Thank you!
