### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE'

### ISSUE THREAD

**Issue by xaviervasques** [Emotiv/cortex-example#118]
Hello, 
Hope someone can help me. I tried to run raw.js and and have got the error below. The headset is connected to Cortex App (EPOC+).
Can you please help me ? 
Thanks

air-de-xav:src xav$ sudo node raw.js 
Password:
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
    at TLSSocket.emit (events.js:203:13)
    at TLSSocket._finishInit (_tls_wrap.js:792:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)
Emitted 'error' event at:
    at ClientRequest.<anonymous> (/Users/xav/Desktop/GitHub/cortex-example/nodejs/node_modules/ws/lib/WebSocket.js:649:10)
    at ClientRequest.emit (events.js:203:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}

**Comment by nguoithichkhampha** [comment]
@xaviervasques this issue is fixed in Cortex v2. 
https://github.com/Emotiv/cortex-v2-example
