### ISSUE TITLE
nodejs: authroize() gives invalid license key

### ISSUE THREAD

**Issue by robbelouwet** [Emotiv/cortex-example#138]
Hi

I'm trying out the nodejs example. Everything works fine until i query the authorize() function. I get hit with an 'Invalid Licens key'

```node
request: 
{"jsonrpc":"2.0","method":"authorize","params:{"clientId":*client ID*,"clientSecret": *secret*,"license":"Pro License","debit":1},"id":4}

response:  {"error":{"code":-32002,"message":"Invalid License Key."},"id":4,"jsonrpc":"2.0"}
TypeError: Cannot read property 'cortexToken' of undefined
    at WebSocket.socket.on (/home/robbe/Desktop/Application/emotiv-deepmind/src/utils/cortex.js:107:57)
    at WebSocket.emit (events.js:203:15)
    at Receiver.receiverOnMessage (/home/robbe/Desktop/Application/emotiv-deepmind/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/robbe/Desktop/Application/emotiv-deepmind/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/home/robbe/Desktop/Application/emotiv-deepmind/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/robbe/Desktop/Application/emotiv-deepmind/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/robbe/Desktop/Application/emotiv-deepmind/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
```

I tried with 'Basic License' or just leaving out the license out entirely because the docs say it's optional. However I keep getting this error. Frankly I think the docs should mention a few example strings of how the license string should look like. I have some idea of what to specify as license, but I just guess it's expecting something like 'Basic License' because example strings aren't mentioned in the docs.

**Comment by robbelouwet** [comment]
So I fixed it...

My client secret and client ID pointed to a cortex APP I created for which I specified it would need raw EEG data (I ticked that EEG box). For this you need a EEG Pro License, only I have the Basic and PRO Lite license. So it said invalid license.

My point still stands about the example strings though. I know it's optional, but I imagine there are people with multiple licenses and it would be nice for them to have example strings to know exactly what string to provide in the 'license' parameter with the 'authorize' request. Because. If the cortex API can figure out what license the user has, and there is no use at all for the user to specify the license, then what's the point of there being a license parameter?
