### ISSUE TITLE
I have an error and I couldn't fix it 

### ISSUE THREAD

**Issue by maitha21** [Emotiv/cortex-example#166]
I am running train.py , my headset is epoc x and I already  got my API license key 
query headset --------------------------------
connect headset --------------------------------
102
Connect headset EPOCX-E20207CC successfully.
request access --------------------------------
authorize --------------------------------
Traceback (most recent call last):
  File "C:\Users\Omait\Downloads\cortex-v2-example-master\cortex-v2-example-master\python\train.py", line 234, in <module>
    t.do_prepare_steps()
  File "C:\Users\Omait\Downloads\cortex-v2-example-master\cortex-v2-example-master\python\train.py", line 51, in do_prepare_steps
    self.c.do_prepare_steps()
  File "C:\Users\Omait\Downloads\cortex-v2-example-master\cortex-v2-example-master\python\cortex.py", line 219, in do_prepare_steps
    self.create_session(self.auth, self.headset_id)
AttributeError: 'Cortex' object has no attribute 'auth'
[Finished in 58.3s]

**Comment by tungntEmotiv** [comment]
Hi @maitha21 ,

I suppose that the "authorize" process might get error lead to error at create_session as you mention. Could you help set debug_mode = True at __init__ () of train.py ? I want to see more log for authorize process .
Thanks
