### ISSUE TITLE
Question: Problem using nodejs/src/events.js

### ISSUE THREAD

**Issue by athergeek** [Emotiv/cortex-example#6]
Operating system: ✍️ WINDOWS 10
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ its coming blank -- just downloaded the code
language version:(nodejs version, ruby version ....) ✍️ nodejs
Cortex version:  ✍️ Not sure, just downloaded the code

---

**I wrote a very simple code using events.js as recommended in documentation. But getting error.**

`const Cortex = require('./lib/cortex')
const onEvent = require('./src/events')

const client = new Cortex({})
const threshold = 0.9;

onEvent(client, threshold, (event) => console.log('got an event!', event))`

**getting following error**

  **C:\projects\emotiv\cortex-example\nodejs\src\events.js:37
    .createSession({status: 'open'})
     ^

TypeError: client.createSession is not a function
    at events (C:\projects\emotiv\cortex-example\nodejs\src\events.js:37:6)
    at Object.<anonymous> (C:\projects\emotiv\cortex-example\nodejs\events-test.js:7:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
PS C:\projects\emotiv\cortex-example\nodejs>**

**Comment by athergeek** [comment]
ok looks like i have to call init( ) and queryheadset( ) first. Following code works


const Cortex = require('./lib/cortex')
const onEvent = require('./src/events'')
const client = new Cortex({})

client.ready.then(() =>
  client.init()
  .queryHeadsets()
  .then(headsets => {
    console.log('headsets', headsets)
          onEvent(client, 0.9, (event) => {
            console.log('got an event!', event)
          })
        })
    )
