### ISSUE TITLE
Feature: Java Example

### ISSUE THREAD

**Issue by MKnierim** [Emotiv/cortex-example#87]
Hi everyone,

I have recently started to develop a Java (JDK 1.8) interface to Cortex Service (1.8.362), using the tyrus & Jetty Websocket implementation (still trying to figure out what works better with less overhead). Unfortunately, I keep running into similar issues that have been posted in issues #5 and #294 (https://github.com/Emotiv/community-sdk/issues/294).

Knowing that some of you have already worked on such implementations (@landret, @cedorland, @ritademolfetta), I was wondering if there is a possibility for you or someone else to share an example of a Java implementation? It seems like more users might have a need for this...

I'll be happy to share my solution too once I get over the "trying to connect to the websocket-server" issues mentioned above...

Best regards,
Michael

**Comment by nguoithichkhampha** [comment]
@MKnierim , the solution is ignore ssl verify . You can referent in here
https://nakov.com/blog/2009/07/16/disable-certificate-validation-in-java-ssl-connections/

**Comment by MKnierim** [comment]
Hello everyone,

thank you @nguoithichkhampha for the recommendation. I have continued with the Jetty websocket libraries and have learned that they provide two different implementations. For reference see: https://examples.javacodegeeks.com/enterprise-java/jetty/jetty-websocket-example/ 

Starting with the example implementations here: https://github.com/jetty-project/embedded-jetty-websocket-examples I have attempted to establish a connection, but have not had any luck. These are the responses I receive (even with the recommended disabling of the SSL handshake):

**Alternative 1: Jetty JSR-356 Implementation**
`public static void main(String[] args) {
        // Disable SSL
        SslContextFactory sec = new SslContextFactory();
        sec.setValidateCerts(false);

        URI uri = URI.create("wss://emotivcortex.com:54321");

        WebSocketClient client = new WebSocketClient();
        try {
            try {
                client.start();

                // The socket that receives events
                EventSocket socket = new EventSocket();
                // Attempt Connect
                Future<Session> fut = client.connect(socket,uri);
                // Wait for Connect
                Session session = fut.get();
                // Send a message
                session.getRemote().sendString("Hello");
                // Close session
                session.close();
            }
            finally {
                client.stop();
            }
        }
        catch (Throwable t) {
            t.printStackTrace(System.err);
        }
    }`

This returns an IOException: "Cannot init SSL" - See:
`java.io.IOException: Cannot init SSL
	at org.eclipse.jetty.websocket.client.io.WebSocketClientSelectorManager.newConnection(WebSocketClientSelectorManager.java:96)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.createEndPoint(SelectorManager.java:735)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processConnect(SelectorManager.java:676)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:640)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:607)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:545)
	at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)`

**Alternative 2: Jetty WebSocket API Implementation**
`public static void main(String[] args) {
        // Disable SSL
        SslContextFactory sec = new SslContextFactory();
        sec.setValidateCerts(false);

        URI uri = URI.create("wss://emotivcortex.com:54321");

        try {
            WebSocketContainer container = ContainerProvider.getWebSocketContainer();

            try {
                // Attempt Connect
                Session session = container.connectToServer(EventSocket.class, uri);
                // Send a message
                session.getBasicRemote().sendText("Hello");
                // Close session
                session.close();
            } finally {
                // Force lifecycle stop when done with container.
                // This is to free up threads and resources that the
                // JSR-356 container allocates. But unfortunately
                // the JSR-356 spec does not handle lifecycles (yet)
                if (container instanceof LifeCycle) {
                    ((LifeCycle) container).stop();
                }
            }
        } catch (Throwable t) {
            t.printStackTrace(System.err);
        }
    }`

This returns an SSLHandshakeException: "General SSLEngine problem" - See:
`javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:516)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:825)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:128)
	at org.eclipse.jetty.websocket.client.io.UpgradeConnection$SendUpgradeRequest.run(UpgradeConnection.java:74)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)`

What could be the cause of this issue? I have validated that CortexService (1.8.325) is running, and that the port is open (as indicated both by OSX Network utility and nmap port scan). Furthermore, I have been able to connect to CortexService via the Node.js example implementation, therefore I no longer believe this is a purely OSX-specific issue. However, could it be related to the JVM? I have been using Java 1.8.0_091 on OSX 10.11.6.

Any more ideas? As I have also encountered a bug in EmotivPro that prevents me to securely collect longer, parallel EEG sessions (i.e. with multiple headsets), I am very much in need to make this work. :/ Any help would be greatly appreciated...

Best regards,
Michael
